INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Alice:Madness Returns", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Alien:Isolation", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Alone in the Dark", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Angry Birds Star Wars", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Angry Birds Trilogy,", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Army of Two", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Army of Two: The 40th Day", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Army of Two: The Devil's Cartel", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Assanssin's Creed", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Assanssin's Creed II", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Assanssin's Creed III", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Assanssin's Creed IV", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Asura's Wrath", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Batman: Arkham Asylum", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Batman: Arkham City", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Batman: Arkham Origins", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Diablo III", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Call of Duty:Black Ops II", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Minecraft", 1, 1, 1, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Saint's Row", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("GTA V", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("DBZ Xenoverse", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Destiny", 0, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Halo 4", 1, 1, 1, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Halo 3", 1, 1, 1, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Halo 2", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Halo", 1, 1, 1, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Saints Row 2", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Saints Row: The Third ", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Saints Row IV", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z BurstLimit", 1, 1, 1, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z Budokai", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z Budokai 2", 1, 1, 1, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z Budokai 3", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z Battle of Z", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z Raging Blast 2", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Ball Z Raging Blast", 1, 1, 1, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Harry Potter and the Deathly Hallows P1", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("The Godfather: The Game", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("The Godfather II", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("G.I.Joe The Rise of Cobra", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Age Inquisition", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Age II", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Age Origins Awakening", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon Age Origins", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dead Space", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dead Space 3", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dante's Inferno", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Crysis", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Crysis 2", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Crysis 3", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Max Payne 3", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Mass Effect", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Mass Effect 2", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Mass Effect 3", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lord of the Rings: War in the North", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lord of the Rings: Battle for Middle-Earth", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lord of the Rings: Conquest", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lego: Star Wars II The Original Trilogy", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lego: Star Wars III", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lego: Star Wars The Complete Saga", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lego: The Hobbit", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Lego: The Lord of the Rings", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Gears of War: Judgement", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Gears of War 3", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Gears of War 2", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Gears of War", 1, 1, 1, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Fable II", 1, 0, 0, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Fable III", 1, 0, 0, 1);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Street Fighter IV", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Ultimate Marvel vs Capcom", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Super Street Fighter IV", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Street Fighter X Tekken", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil Revelations 2", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil Revelations", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil Operation Raccoon City", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil 6", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil 5", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil 4", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Resident Evil", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Remember Me", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Dragon's Dogma", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("DMC: Devil May Cry", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Devil May Cry 4", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Red Dead Redemption: Undead Nightmare", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Red Dead Redemption", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("L.A. Noire", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Watch Dogs", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("TMNT:Teenage Mutant Ninja Turtles", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("South Park: The Stick of Truth", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Prince of Persia", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Prince of Persia The Forgotten Sands", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Naruto The Broken Bond", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Naruto Rise of a Ninja", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("FarCry 2", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("FarCry 3", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("FarCry 4", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("FarCry Instincts", 1, 1, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Captain America Super Soldier", 1, 0, 0, 0);
INSERT INTO game_modes (title, single_player, multiplayer, local_four, co_op_four) values ("Thor: God of Thunder", 1, 0, 0, 0);

