INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Alice:Madness Returns", "AA", "Platform", "M", "6/14/2011","Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Alien:Isolation", "SurvHor", "Stealth", "M", "10/7/2014", "Sega");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Alone in the Dark", "Survival Horror", "null", "M", "6/23/2008", "Atari");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Angry Birds Star Wars", "Puzzle", "null", "E", "11/8/2012", "Rovio Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Angry Birds Trilogy,", "Puzzle", "null", "E", "9/25/2007", "Activision");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Army of Two", "3PS", "null", "M", "3/6/2008","Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Army of Two: The 40th Day", "3PS", "null", "RP", "1/12/2010", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Army of Two: The Devil's Cartel", "3PS", "null", "RP", "3/26/2013", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Assanssin's Creed", "A&A", "Stealth", "M", "11/13/2007", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Assanssin's Creed II", "A&A", "Stealth", "M", "11/17/2009", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Assanssin's Creed III", "A&A", "Stealth", "M", "10/30/2012", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Assanssin's Creed IV", "A&A", "Stealth", "M", "10/29/2013", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Asura's Wrath", "A&A", "H&S", "T", "2/21/2012", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Batman: Arkham Asylum", "A&A", "null", "T", "8/25/2009", "Warner Bros. Interactive Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Batman: Arkham City", "A&A", "null", "T", "10/18/2011", "Warner Bros. Interactive Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Batman: Arkham Origins", "A&A", "Stealth", "T", "10/25/2013", "Warner Bros. Interactive Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Diablo III", "ARPG", "H&S", " M", "8/19/2014", "Blizzard Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Call of Duty:Black Ops II", "FPS", "null", "M", "11/12/2012", "Activision");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Minecraft", "Sandbox", "Survival", "E", "11/18/2011", "Mojang");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Saint's Row", "A&A", "null", "M", "8/29/2006","THQ");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("GTA V", "A&A", "Sandbox", "M", "11/18/2014",  "Rockstar Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("DBZ Xenoverse", "TrF", "RP", "M", "2/27/2015", "Bandai Namco Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Destiny", "ARPG", "FPS", "M", "9/9/2014", "Activision");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Halo 4", "FPS", "null", "M", "11/6/2012", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Halo 3", "FPS", "null", "M", "9/25/2007", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Halo 2", "FPS", "null", "M", "11/19/2004", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Halo", "FPS", "null", "M", "11/15/2001", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Saints Row 2","A&A","null","18+", "10/14/2008", "THQ");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Saints Row: The Third ","A&A","null","M", "11/15/2011", "THQ");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Saints Row IV","A&A","null","M", "08/20/2013", "Deep Silver");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z BurstLimit","Versus fighting", "null", "12+", "06/10/2008", "Atari");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z Budokai","Versus fighting", "null", "T", "12/2/2002", "Atari");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z Budokai 2","Versus fighting", "null", "T", "12/4/2003", "Atari");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z Budokai 3","Versus fighting", "null", "T", "11/16/2004", "Atari");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z Battle of Z", "Fighting RPG", "null", "T", "01/28/2014", "Bandai Namco Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z Raging Blast 2", "Versus fighting", "null", "T", "11/2/2010", "Bandai Namco Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Ball Z Raging Blast", "Versus fighting", "null", "T", "11/10/2009", "Bandai Namco Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Harry Potter and the Deathly Hallows P1", "3PS", "Stealth", "T", "11/16/2010", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("The Godfather: The Game", "A&A", "Sandbox", "M", "03/21/2006", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("The Godfather II", "A&A", "Sandbox", "M", "04/7/2009", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("G.I.Joe The Rise of Cobra", "A&A", "null", "T", "08/4/2009", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Age Inquisition", "ARPG", "null", "M", "11/18/2014", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Age II", "ARPG", "null", "M", "03/08/2011", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Age Origins Awakening", "ARPG", "null", "M", "03/16/2010", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon Age Origins", "ARPG", "null", "M", "11/03/2009", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dead Space", "SurvHor", "null", "18+", "10/13/2008", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dead Space 3", "3PS", "SurvHor", "M", "02/05/2013", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dante's Inferno", "H&S", "A&A", "M", "02/09/2010", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Crysis", "FPS", "null", "M", "11/13/2007", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Crysis 2", "FPS", "null", "M", "03/22/2011", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Crysis 3", "FPS", "null", "M", "02/19/2013", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Max Payne 3", "3PS", "null", "M", "05/15/2015", "Rockstar Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Mass Effect", "ARPG", "3PS", "M", "11/16/2007", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Mass Effect 2", "ARPG", "3PS", "M", "01/26/2010", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Mass Effect 3", "ARPG", "3PS", "M", "03/06/2012", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lord of the Rings: War in the North", "ARPG", "H&S", "M", "11/01/2011", "Warner Bros. Interactive Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lord of the Rings: Battle for Middle-Earth", "Real-Time Strategy", "null", "T", "3/02/2006", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lord of the Rings: Conquest", "A&A", "null", "T", "01/09/2009", "Electronic Arts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lego: Star Wars II The Original Trilogy", "A&A", "Platform", "E", "09/11/2006", "LucasArts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lego: Star Wars III", "A&A", "Platform", "E", "03/22/2011", "LucasArts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lego: Star Wars The Complete Saga", "A&A", "Platform", "E", "11/06/2007", "LucasArts");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lego: The Hobbit", "A&A", "Platform", "E", "04/08/2014", "Warner Bros. Interactive Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Lego: The Lord of the Rings", "A&A", "Platform", "E", "11/13/2012", "Warner Bros. Interactive Entertainment");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Gears of War: Judgement", "3PS", "null", "M", "03/19/2013", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Gears of War 3", "3PS", "null", "M", "09/20/2011", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Gears of War 2", "3PS", "null", "M", "11/07/2008", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Gears of War", "3PS", "null", "M", "11/07/2006", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Fable II", "ARPG", "null", "M", "09/21/2008", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Fable III", "ARPG", "null", "M", "10/26/2010", "Microsoft Game Studios");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Street Fighter IV", "Versus fighting", "null", "T", "02/17/2009", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Ultimate Marvel vs Capcom", "Versus fighting", "null", "T", "11/15/2011", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Super Street Fighter IV", "Versus fighting", "null", "T", "04/27/2010", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Street Fighter X Tekken", "Versus fighting", "null", "T", "03/06/2012", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil Revelations 2", "SurvHor", "null", "M", "03/03/2015", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil Revelations", "SurvHor", "null", "M", "01/26/2012", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil Operation Raccoon City", "SurvHor", "3PS", "M", "03/20/2012", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil 6", "A&A", "3PS", "M", "10/02/2012", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil 5", "A&A", "3PS", "M", "03/05/2009", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil 4", "SurvHor", "3PS", "M", "01/11/2005", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Resident Evil", "SurvHor", "3PS", "M", "03/22/2002", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Remember Me", "A&A", "null", "M", "06/03/2015", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Dragon's Dogma", "ARPG", "H&S", "M", "05/22/2012", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("DMC: Devil May Cry", "A&A", "H&S", "M", "01/15/2013", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Devil May Cry 4", "A&A", "H&S", "M", "06/18/2015", "Capcom");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Red Dead Redemption: Undead Nightmare", "A&A", "Sandbox", "M", "10/26/2010", "RockStar Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Red Dead Redemption", "A&A", "Sandbox", "M", "05/18/2010", "RockStar Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("L.A. Noire", "A&A","null", "M", "05/17/2011", "RockStar Games");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Watch Dogs", "A&A", "null", "M", "05/27/2014", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("TMNT:Teenage Mutant Ninja Turtles", "A&A", "null", "E", "05/20/2007", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("South Park: The Stick of Truth", "RP", "null", "M", "03/04/2014", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Prince of Persia", "A&A", "H&S", "T", "12/02/2008", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Prince of Persia The Forgotten Sands", "A&A", "H&S", "T", "05/18/2010", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Naruto The Broken Bond", "Fighter", "A&A", "T", "11/18/2008", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Naruto Rise of a Ninja", "Fighter", "RPG", "T", "11/01/2007", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("FarCry 2", "FPS", "null", "M", "10/21/2008", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("FarCry 3", "FPS", "A&A", "M", "12/4/2012", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("FarCry 4", "FPS", "A&A", "M", "11/18/2014", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("FarCry Instincts", "FPS", "A&A", "M", "09/27/2005", "Ubisoft");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Captain America Super Soldier", "A&A", "null", "T", "07/19/2011", "Sega");
INSERT INTO games (title, primary_genre, sub_genre, rating, release_date, p_name) values ("Thor: God of Thunder", "A&A", "null", "T", "05/03.2011", "Sega");